### ISSUE TITLE
Looking for instructions

### ISSUE THREAD

**Issue by oedm** [quintusl/mblusb#1]
Hello,

i could successfully read by current layout:
```
+++ Matrix discovery and layout configuration tool +++

Device found: No. 10   Vendor: 4b3   Name: 1   Product: 301c   Name: 2   Bus: 1   Address: 15

Number of layers: 2

Layer 1

    C1    C2    C3    C4    C5    C6    C7    C8    C9    C10   C11   C12   C13   C14   C15   C16   C17   C18   C19   C20   

R1  384   82    99    98    0     52    0     63    11    62    10    61    0     41    0     0     0     0     94    93    
R2  92    47    64    48    28    42    23    60    257   43    258   0     0     74    75    73    76    45    65    46    
R3  35    66    34    59    58    53    0     260   70    77    78    69    68    39    38    37    36    67    33    32    
R4  31    30    0     0     71    87    97    96    95    19    18    12    24    0     21    8     26    20    0     0     
R5  0     88    91    90    89    51    15    14    13    49    9     7     22    4     0     0     0     72    85    84    
R6  83    0     55    54    16    40    25    6     27    29    288   1025  320   80    86    79    81    56    0     0     
R7  17    44    5     0     0     0     0     0     384   128   99    98    0     52    0     63    11    62    10    61    
R8  0     41    0     0     0     0     94    93    92    47    64    48    28    42    23    60    257   43    258   0     

Layer 2

    C1    C2    C3    C4    C5    C6    C7    C8    C9    C10   C11   C12   C13   C14   C15   C16   C17   C18   C19   C20   

R1  

Enter filename: old-layout
```

But i'm not quite sure which values to change. Based on the test program `xev`, my *left ctrl* and the *left alt* key are misconfigured, but it seems the values above aren't those keycodes.

Key | current keycode | desired keycode
--- | --- | ---
L_ALT | 134 | 64
L_CTRL | 64 | 37

Thanks a lot!

**Comment by quintusl** [comment]
Hello,

I add some sample layouts in https://github.com/quintusl/mblusb/tree/master/sample_layouts. You may get more details from the files. Furthermore, you may look into https://github.com/quintusl/mblusb/blob/master/src/layout.h for the key codes.

The GUI tools is a more user friendly way to configure the layouts. You may also want to try:
https://github.com/Arakula/blusb_gui

Hope these help.

**Comment by chancefavorsthepreparedmind** [comment]
krikey, there's a bug in me source file! The layout table didn't get drawn correctly because I falsely assigned a new value to a counter variable within a for loop in read_layout(), it's fixed now, will update the repo in a minute

**Comment by oedm** [comment]
Thanks for your help! I was able to reset my layout with the blusb_gui tool.
Let me know when I can help somebody with testing or so.
